// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Bitcoin.Api.Client.AutoGenerated.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class BccBalanceResponse
    {
        /// <summary>
        /// Initializes a new instance of the BccBalanceResponse class.
        /// </summary>
        public BccBalanceResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BccBalanceResponse class.
        /// </summary>
        public BccBalanceResponse(decimal? balance = default(decimal?))
        {
            Balance = balance;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "balance")]
        public decimal? Balance { get; set; }

    }
}
