// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Bitcoin.Api.Client.AutoGenerated.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class CommitmentBroadcastResponse
    {
        /// <summary>
        /// Initializes a new instance of the CommitmentBroadcastResponse
        /// class.
        /// </summary>
        public CommitmentBroadcastResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CommitmentBroadcastResponse
        /// class.
        /// </summary>
        public CommitmentBroadcastResponse(IList<CommitmentBroadcastInfo> commitmentBroadcasts = default(IList<CommitmentBroadcastInfo>))
        {
            CommitmentBroadcasts = commitmentBroadcasts;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "commitmentBroadcasts")]
        public IList<CommitmentBroadcastInfo> CommitmentBroadcasts { get; set; }

    }
}
