// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

using System.Collections.Generic;
using Newtonsoft.Json;

namespace Lykke.Bitcoin.Api.Client.AutoGenerated.Models
{
    public partial class GetAllWalletsResult
    {
        /// <summary>
        /// Initializes a new instance of the GetAllWalletsResult class.
        /// </summary>
        public GetAllWalletsResult()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GetAllWalletsResult class.
        /// </summary>
        public GetAllWalletsResult(IList<string> multisigs = default(IList<string>))
        {
            Multisigs = multisigs;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "multisigs")]
        public IList<string> Multisigs { get; set; }

    }
}
