// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Bitcoin.Api.Client.AutoGenerated.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class MultisigBalanceInfo
    {
        /// <summary>
        /// Initializes a new instance of the MultisigBalanceInfo class.
        /// </summary>
        public MultisigBalanceInfo()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MultisigBalanceInfo class.
        /// </summary>
        public MultisigBalanceInfo(string multisig = default(string), decimal? clientAmount = default(decimal?), decimal? hubAmount = default(decimal?), System.DateTime? updateDt = default(System.DateTime?))
        {
            Multisig = multisig;
            ClientAmount = clientAmount;
            HubAmount = hubAmount;
            UpdateDt = updateDt;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "multisig")]
        public string Multisig { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "clientAmount")]
        public decimal? ClientAmount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hubAmount")]
        public decimal? HubAmount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "updateDt")]
        public System.DateTime? UpdateDt { get; set; }

    }
}
