// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

using Newtonsoft.Json;

namespace Lykke.Bitcoin.Api.Client.AutoGenerated.Models
{
    public partial class OffchainCommitmentResponse
    {
        /// <summary>
        /// Initializes a new instance of the OffchainCommitmentResponse class.
        /// </summary>
        public OffchainCommitmentResponse()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the OffchainCommitmentResponse class.
        /// </summary>
        public OffchainCommitmentResponse(string transactionHex = default(string))
        {
            TransactionHex = transactionHex;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "transactionHex")]
        public string TransactionHex { get; set; }

    }
}
