// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Bitcoin.Api.Client.AutoGenerated.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class OffchainBalanceInfo
    {
        /// <summary>
        /// Initializes a new instance of the OffchainBalanceInfo class.
        /// </summary>
        public OffchainBalanceInfo()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the OffchainBalanceInfo class.
        /// </summary>
        public OffchainBalanceInfo(decimal? clientAmount = default(decimal?), decimal? hubAmount = default(decimal?), string transactionHash = default(string), bool? actual = default(bool?))
        {
            ClientAmount = clientAmount;
            HubAmount = hubAmount;
            TransactionHash = transactionHash;
            Actual = actual;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "clientAmount")]
        public decimal? ClientAmount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hubAmount")]
        public decimal? HubAmount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "transactionHash")]
        public string TransactionHash { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "actual")]
        public bool? Actual { get; set; }

    }
}
