using System;
using Lykke.Bitcoin.Api.Client.AutoGenerated.Models;
using Lykke.Bitcoin.Api.Client.BitcoinApi.Models;

// ReSharper disable once CheckNamespace
namespace Lykke.Bitcoin.Api.Client.BitcoinApi
{
    public partial class BitcoinApiClient : IBitcoinApiClient
    {
        private readonly Lykke.Bitcoin.Api.Client.AutoGenerated.BitcoinApi _apiClient;

        public BitcoinApiClient(string apiUrl)
        {
            _apiClient = new Lykke.Bitcoin.Api.Client.AutoGenerated.BitcoinApi(new Uri(apiUrl));
            _apiClient.SetRetryPolicy(null);
        }

        private T PrepareResult<T>(object response, Func<object, T> convert) where T : Response
        {
            if (response is ApiException error)
            {
                var instance = Activator.CreateInstance<T>();
                instance.Error = new ErrorResponse { Code = error.Error.Code, Message = error.Error.Message };
                return instance;
            }
            var converted = convert(response);
            if (converted != null)
                return converted;
            throw new ArgumentException("Unkown response object");
        }
    }
}
