using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Bitcoin.Api.Client.AutoGenerated;
using Bitcoin.Api.Client.AutoGenerated.Models;
using Bitcoin.Api.Client.BitcoinApi.Models;

// ReSharper disable once CheckNamespace
namespace Bitcoin.Api.Client.BitcoinApi
{
    public partial class BitcoinApiClient
    {
        public async Task<AllWalletsResponse> GetAllWallets()
        {
            var response = await _apiClient.ApiWalletAllGetAsync();
            return PrepareResult(response, o =>
            {
                if (o is GetAllWalletsResult model)
                    return new AllWalletsResponse
                    {
                        Multisigs = model.Multisigs.ToList()
                    };
                return null;
            });
        }

        public async Task<Wallet> GetWallet(string clientPubKey)
        {
            var response = await _apiClient.ApiWalletByClientPubKeyGetAsync(clientPubKey);
            return PrepareResult(response, o =>
            {
                if (o is GetWalletResult model)
                    return new Wallet
                    {
                        Multisig = model.MultiSigAddress,
                        ColoredMultisig = model.ColoredMultiSigAddress
                    };
                return null;
            });
        }
    }
}
